// transplanted from https://github.com/jgraph/drawio-tools/blob/d46977060ffad70cae5a9059a2cbfcd8bcf420de/tools/convert.html
import pako from 'pako';

import { isMxfileData } from './mxfile.js';

const unconpressedDataRegexp = /<mxGraphModel/;
const validateUncompressedData = (input: string): boolean => {
  return unconpressedDataRegexp.test(input);
};

const validateCompressedData = (input: string): boolean => {
  let data = input;

  try {
    data = Buffer.from(data, 'base64').toString('binary');
  } catch (e) {
    throw new Error(`Base64 to binary failed: ${e}`);
  }

  if (data.length > 0) {
    try {
      data = pako.inflateRaw(
        Uint8Array.from(data, (c) => c.charCodeAt(0)),
        { to: 'string' },
      );
    } catch (e) {
      throw new Error(`inflateRaw failed: ${e}`);
    }
  }

  try {
    data = decodeURIComponent(data);
  } catch (e) {
    throw new Error(`decodeURIComponent failed: ${e}`);
  }

  return true;
};

const escapeHTML = (string): string => {
  if (typeof string !== 'string') {
    return string;
  }
  return string.replace(/[&'`"<>]/g, (match): string => {
    return (
      {
        '&': '&amp;',
        "'": '&#x27;',
        '`': '&#x60;',
        '"': '&quot;',
        '<': '&lt;',
        '>': '&gt;',
      }[match] ?? match
    );
  });
};

export const generateMxgraphData = (
  code: string,
  isDarkMode: boolean,
): string => {
  const trimedCode = code.trim();
  if (!trimedCode) {
    return '';
  }

  // Multi-page format: the stored code already is a full <mxfile> holding every
  // page. Pass it through untouched so no page is dropped, and enable page
  // navigation so the extra pages are reachable in the viewer.
  const isMultiPage = isMxfileData(trimedCode);

  let xml: string;
  if (isMultiPage) {
    xml = trimedCode;
  } else {
    // Legacy single-page format: the stored code is a single diagram's inner
    // XML, so it must be wrapped in an <mxfile>/<diagram>.
    // Evaluate the code is whether uncompressed data that are generated by v21.1.0 or above
    // see: https://github.com/jgraph/drawio/issues/3106#issuecomment-1479352026
    const isUncompressedData = validateUncompressedData(trimedCode);
    if (!isUncompressedData) {
      validateCompressedData(trimedCode);
    }

    xml = `
    <mxfile version="6.8.9" editor="www.draw.io" type="atlas">
      <mxAtlasLibraries/>
      <diagram>${trimedCode}</diagram>
    </mxfile>
  `;
  }

  const mxGraphData = {
    editable: false,
    highlight: '#0000ff',
    nav: isMultiPage,
    toolbar: isMultiPage ? 'pages' : null,
    edit: null,
    resize: true,
    lightbox: 'false',
    xml,
    // To sync with GROWI app's color mode, pass 'dark' when the app is in dark mode. 'auto' would read OS color scheme via window.matchMedia instead.
    // refs: https://github.com/jgraph/drawio/blob/eaae294cba5010e3a9d04b685407e79512f88d2d/src/main/webapp/js/diagramly/GraphViewer.js#L888-L892
    'dark-mode': isDarkMode ? 'dark' : undefined,
  };

  return escapeHTML(JSON.stringify(mxGraphData));
};
